### ISSUE TITLE
[backend & frontend] Chat interface must-do

### ISSUE THREAD

**Issue by seohl16** [ft-nobrand/ft_transcendence#113]
# TO-DO LIST 
## backend 
- [ ] 

## frontend 
- [ ] 프로필 보기 -> 프로필 사이트로 이동 ex) profile/13 
- [ ] 게임 초대를 위해서 소켓 연결하기 
- [ ] 게임 초대를 요청하기 
- [ ] 게임 초대 받으면 알림 오기 (modal 등으로) 
- [ ] 사용자 리스트에서 접속 상태 보이기 user.status 0 1 2 사용하면 됨 
- [ ]

**Comment by seohl16** [comment]
## 113_chat_dm_ branch commit 내용 
## 백엔드 부분 
### chat.gateway.ts
- 블락할 때 빈 배열 에러 수정 
- saveuserstatus할 때 유저 못 찾는 경우 에러 수정 
- deleteRoom msg: 'success', roomId: chatRoomId, roomid 값도 돌려주도록 수정 
- private room 만들 때 패스워드가 안 들어온 경우 던져지는 에러 수정 
- joinRoom [msg](msg: 'success', roomId: chatRoomId, roomid값도 돌려주도록 수정 
- emitRoomInfoToUser 함수에서 userid 값도 고려하도록 수정 
- password가 잘못되었을 때 던지는 에러가 Unauthorized로만 코드가 돌려지도록 수정 
- changePassword emit에서 실패했을 때 msg: 'fail', err:e 에러 내용도 돌려주도록 수정 

## 프론트엔드 부분 
### ChatSideListForm
- 블락하기를 눌렀을 때 getRoomInfo, receiveChat을 emit해서 다시 방 정보를 받도록 수정 
- '메시지 보내기'를 삭제하고, DM하기를 만들어서 joinDM 소켓이랑 연결 
### Index.js, [chatId].js
- 'joinDM' on socket을 켜서 DM하기를 누르면 방을 이동하도록 수정

**Comment by seohl16** [comment]
# TO-DO LIST 
## backend 
- [x] joinDM 이후 새로고침할 수 있게 emit handshake 하기 
- [ ] kick했을 때 에러 메시지 제대로 주기 

## frontend 
- [x] messageId에 Setsocket 수정하기 (이상했음)
- [ ] kick하고 나서 error message따라서 alert제대로 주고, redirect Main 무조건 되도록은 안되게 고치기. 
- [ ]

**Comment by seohl16** [comment]
# TO-DO LIST 
## backend 
- [x] receiveChat /DM 할 때 너무 소켓 남발하는 에러 해결하기 
- [x] game gateway에서 handle connection할 때 handshake 안하고, client game/index.tsx에서 하도록 수정 
- [x] game gateway에서 user이 ingame일 때 초대를 보내지 않도록 inviteGame 수정 
- [x] 필요 없는 콘솔 제거, 필요없는 success emit 제거 

## frontend 
- [x] dm할 때 소켓 많이 보내지 않도록 dmhandshake, chathandshake 추가 
- [x] game/index.tsx 에도 notify, handshake emit 추가하기 
- [x] 채팅 Popup 해결 
- [x] messageSideList, chatSideList에서 getRoomInfo, receiveChat 삭제 (main page)에서도 이미 하는 소켓이라 할 필요가 없음 

```javascript
    socket.on('dmhandshake', () => {
      socket.emit(`receiveDM`, { dmRoomId: roomId });
    })
```
