### ISSUE TITLE
[frontend] 채팅 관련 페이지 모든 이슈

### ISSUE THREAD

**Issue by Eomhyunjun** [ft-nobrand/ft_transcendence#29]
[공통사항]
- [x] 간단 css 입히기   |   #8 

[채팅 페이지]
- [x] 더미 데이터로 백엔드 없이 동작하게 만들기 | #39
- [x] 채팅방 리스트 만들기    |   #8 
- [x] 접속 유저 리스트 만들기   |   #8
- [x] 참여중인 채팅채널 만들기 | #39
- [x]  채팅 생성 버튼 클릭 시 채팅 생성 팝업 | #39
   - [x] 팝업에 채팅방 제목 비밀번호 입력 | #39
- [x] 공개 채팅 채널 접속 | #39
- [x] 잠금 채널 접속
    - [x] 비밀번호 입력 팝업 띄우기 #60
    - [x] 백엔드로 비밀번호 전송 후 확인 | #60
    - [x] 맞으면 접속, 아니면 비밀번호 틀렸다고 알려주기
 
[채팅 내부 페이지]
- [x] 채팅 내부 페이지 생성 | #39
   - [x] 채팅 헤더 | #39
      - [x] 채팅하기 글 띄우기 | #39
      - [x] 채팅방 설정 버튼 생성 | #39
         - [x] 강퇴하기 | #39
         - [x] 권한주기 | #39
         - [x] 뮤트 | #39
         - [x] 밴 | #39
   - [x] 채팅 바디 | #39
      - [x] 채팅 내역 띄워주기 | #39
      - [x] 채팅 내부 참여자 목록 생성 | #39
      - [x] 참여자 클릭 시 모달 생성 | #39
         - [x] 친구 추가 팝업 | #39
         - [x] 프로필 페이지(전적 보여주기) | #39
         - [x] 게임 초대 전송 | #39
         - [x] 메세지 보내기(갠톡) | #39
         - [x] 차단하기 | #39
   - [x] 채팅 바텀 | #39
      - [x] 채팅 입력 전송 버튼 | #39
      - [x] 채팅 나가기 버튼 | #39

[ 추가사항 ]
- [x] 백엔드와 통신
- [x] CSS 열심히 입히기
